version: '3'
 
services:
  mysqltest:
    image: mysql/mysql-server
    container_name: mysqltest
    expose:
      - 3306
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_DATABASE: test
    volumes:
       - /docker-compose-app/permission.sql:/docker-entrypoint-initdb.d/permission.sql
       

