version: '3'
 
services:
  mysql02:
    image: mysql/mysql-server
    container_name: mysql02
    expose:
      - 3306
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_DATABASE: springboot
  mongo02:
    image: mongo
    container_name: mongo02
    expose:
      - 27017
  springbootmysql:
    depends_on:
      - mysql02
      - mongo02
    build:
      context: .
      dockerfile: SpringBootDockerJenkins
    image: springbootintegration
    container_name: springbootmysql
    links:
      - mysql02
      - mongo02
    expose:
      - 8080
    environment:
      db_type: mysql
      mysql_host: mysql02
      mongo_host: mongo01
      spring_rest_controller_enabled: "false"
  springbootmongorest:
    depends_on:
      - mysql02
      - mongo02
      - springbootmysql
    image: springbootintegration
    container_name: springbootmongorest
    links:
      - mysql02
      - mongo02
    expose:
      - 8080
    environment:
      db_type: mongo
      mysql_host: mysql02
      mongo_host: mongo01
      spring_rest_controller_enabled: "true"

