version: '3'
 
services:
  mysql02:
    image: mysql/mysql-server
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m
      timeout: 10m
      retries: 2
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 512M
      restart_policy:
        condition: none
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_DATABASE: springboot
    networks:
      - backend
networks:
  backend:

